"""
Generates pytest integration test code from CaptureRecord objects.
"""
import json
import re
from typing import Any

from ..pipeline.state_inferrer import infer_fixtures, resolve_body_refs


_TEMPLATE = '''\
def {test_name}():
    # Arrange
{arrange}
    # Act
    response = client.{method}(
        "{path}",{body_arg}{headers_arg}
    )

    # Assert
    assert response.status_code == {status_code}
{assertions}
'''


def generate_test(record) -> str:
    test_name = _make_test_name(record.method, record.path)
    fixtures = infer_fixtures(record.req_body, record.req_headers)
    body = resolve_body_refs(record.req_body, fixtures)

    arrange = "\n".join(f"    {f}" for f in fixtures) if fixtures else "    pass"
    body_arg = _format_body(body)
    headers_arg = _format_headers(record.req_headers)
    assertions = _generate_assertions(record.resp_body, record.status_code)

    return _TEMPLATE.format(
        test_name=test_name,
        arrange=arrange,
        method=record.method.lower(),
        path=record.path,
        body_arg=body_arg,
        headers_arg=headers_arg,
        status_code=record.status_code,
        assertions=assertions,
    )


def generate_module(records: list, service: str) -> str:
    """Generate a complete pytest module for a list of records (same endpoint)."""
    header = f'''\
# Generated by Httrace — {len(records)} interactions captured
# Service: {service}
# DO NOT EDIT — re-run `httrace generate` to update
import pytest
from tests.conftest import client


'''
    tests = "\n\n".join(generate_test(r) for r in records)
    return header + tests


def _make_test_name(method: str, path: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]", "_", path).strip("_")
    slug = re.sub(r"_+", "_", slug)
    return f"test_{method.lower()}_{slug}"


def _format_body(body: Any) -> str:
    if not body:
        return ""
    raw = json.dumps(body, indent=8)
    # Replace string refs back to variable references
    raw = re.sub(r'"__REF_(\w+)__"', lambda m: f"{m.group(1)}.id", raw)
    return f"\n        json={raw},"


def _format_headers(headers: dict) -> str:
    if not headers:
        return ""
    filtered = {k: v for k, v in headers.items() if k.lower() not in ("host", "content-length")}
    if not filtered:
        return ""
    return f"\n        headers={json.dumps(filtered)},"


def _generate_assertions(resp_body: Any, status_code: int) -> str:
    lines = []
    if isinstance(resp_body, list):
        lines.append("    data = response.json()")
        lines.append("    assert isinstance(data, list)")
        if resp_body:
            first = resp_body[0]
            if isinstance(first, dict):
                for key in first:
                    lines.append(f'    assert "{key}" in data[0]')
        return "\n".join(lines)

    if not isinstance(resp_body, dict):
        return ""

    # Always-present fields → assert presence
    for key, value in resp_body.items():
        if isinstance(value, (str, int, float, bool)) and not _looks_like_id(key):
            # Stable enum-like strings get value assertion
            if isinstance(value, str) and len(value) < 32 and value.isalpha():
                lines.append(f'    assert response.json()["{key}"] == "{value}"')
            else:
                lines.append(f'    assert "{key}" in response.json()')
        else:
            lines.append(f'    assert "{key}" in response.json()')

    return "\n".join(lines)


def _looks_like_id(key: str) -> bool:
    return any(seg in key.lower() for seg in ("id", "uuid", "token", "ref"))
